# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
exclude: [vendor]
title: Tony Mkhael
email: tony.mkhael@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonymkhael.github.io" # the base hostname & protocol for your site
author:
    name: Tony Mkhael
    description: "Simplicity is the ultimate form of sophistication"
    copyright: "&copy; Tony Mkhael"
    gravatar: 14d15a4a8d6f362e0a13ab8ca06e6e02 # md5 hash of your email address
    feedburner: tonymkhael
    contact:
      email: mailto:tony.mkhael@gmail.com
      github: https://www.github.com/tonymkhael
      twitter: https://www.twitter.com/tonymkhael
      linkedin:  https://www.linkedin.com/in/tonymkhael

# Build settings
markdown: kramdown
gems:
  - jekyll-asciidoc
  - jekyll-paginate
  - jekyll-sitemap

asciidoctor:
  attributes:
    - idprefix=_
    - idseparator=_
    - source-highlighter=pygments
    - pygments-css=style
    - icons=font

# Navigation (2nd level links supported)
nav:
  Blog:
    - '/'
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://tonymkhael.github.io/'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
paginate: 3
paginate_path: '/page:num'
permalink: pretty
sass:
  style: compressed
  sass_dir: _scss
mathjax: true # whether support mathjax
google_analytics_token: 'UA-67595221-2' # leave blank if you don't want google analytics
disqus_short_name: 'tonymkhael' # leave blank if you don't want disqus
